#AUGUSTO LUIZ MARIM - CC3M

create database CC3M_UVV;

use CC3M_UVV;

create table if not exists CIDADES(
CIDADE_COD INT primary key auto_increment,
CIDADE_NOME VARCHAR(50) NOT NULL
);

create table if not exists BANCO(
BANCO_COD INT primary key auto_increment,
BANCO_SALDO_ATUAL FLOAT NOT NULL,
BANCO_NOME VARCHAR(50) NOT NULL
);

create table if not exists EMPRESAS(
EMPRESA_COD INT primary key auto_increment,
EMPRESA_RAZ_SOC VARCHAR(45) NOT NULL,
EMPRESA_TIPO ENUM('FORNECEDOR', 'CLIENTE', 'AMBOS') NOT NULL,
EMPRESA_CNPJ_CPF VARCHAR(14) NOT NULL,
EMPRESA_EMAIL VARCHAR(50) NOT NULL,
EMPRESA_TELEFONE VARCHAR(15) NOT NULL,
EMPRESA_RUA VARCHAR(50) NOT NULL,
EMPRESA_NUMERO_RUA INT,
EMPRESA_BAIRRO VARCHAR(50) NOT NULL,
EMPRESA_ESTADO VARCHAR(50) NOT NULL,
EMPRESA_PAIS VARCHAR(50) NOT NULL,
EMPRESA_CEP VARCHAR(50) NOT NULL,
EMPRESA_CIDADE INT NOT NULL,

constraint FK_CIDADE_EMPRESA foreign key (EMPRESA_CIDADE)
references CIDADES(CIDADE_COD)
);

create table if not exists CONTAS_PAGAR(
PAGAR_COD INT primary key auto_increment,
PAGAR_VALOR FLOAT NOT NULL,
PAGAR_DATA_VENCIMENTO DATE NOT NULL,
PAGAR_DATA_EMISSAO DATE NOT NULL,
PAGAR_COD_BARRAS TEXT NOT NULL,
PAGAR_EMPRESA INT NOT NULL,
PAGAR_BANCO INT NOT NULL,

constraint FK_EMPRESA_PAGAR foreign key (PAGAR_EMPRESA)
references EMPRESAS(EMPRESA_COD),

constraint FK_BANCO_PAGAR foreign key (PAGAR_BANCO)
references BANCO(BANCO_COD)
);

create table if not exists CONTAS_RECEBER(
RECEBER_COD INT primary key auto_increment,
RECEBER_VALOR FLOAT NOT NULL,
RECEBER_DATA_VENCIMENTO DATE NOT NULL,
RECEBER_DATA_EMISSAO DATE NOT NULL,
RECEBER_COD_BARRAS TEXT NOT NULL,
RECEBER_EMPRESA INT NOT NULL,
RECEBER_BANCO INT NOT NULL,

constraint FK_EMPRESA_RECEBER foreign key (RECEBER_EMPRESA)
references EMPRESAS(EMPRESA_COD),

constraint FK_BANCO_RECEBER foreign key (RECEBER_BANCO)
references BANCO(BANCO_COD)
);


